#!/usr/bin/python3
""" This module has the raise_exception_message"""
def raise_exception_msg(message=""):
    raise NameError(message)
